name: CI-Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Assemble
        run: ./gradlew assemble

      - name: Run test suite
        run: ./gradlew test :sharedLogic:allTests :sharedUI:allTests --console=plain
